$(document).ready(function() {
  console.log("I'm main !");

  var contentNewSurvey = "<form action='#'> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='nameNewSurvey'> <label class='mdl-textfield__label'>Nom du Sondage</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='content'> <label class='mdl-textfield__label'>Contenu (100 caractères max)</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='choice1'> <label class='mdl-textfield__label'>Choix 1 (Obligatoire)</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='choice2'> <label class='mdl-textfield__label'>Choix 2 (Obligatoire)</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='choice3'> <label class='mdl-textfield__label'>Choix 3 (Optionnel)</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='text' name='choice4'> <label class='mdl-textfield__label'>Choix 4 (Optionnel)</label> </div></form>"

  var contentLogin = "<form action='#'> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='mail' name='login'> <label class='mdl-textfield__label'>Mail</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='password' name='password'> <label class='mdl-textfield__label'>Mot de passe</label> </div></form>"

  var contentSignup = "<form action='#'> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='mail' name='login'> <label class='mdl-textfield__label'>Mail</label> </div> <div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='password' name='password'> <label class='mdl-textfield__label'>Mot de passe</label> </div><div class='mdl-textfield mdl-js-textfield mdl-textfield--full-width mdl-textfield--floating-label'> <input class='mdl-textfield__input' type='password' name='passwordValidate'> <label class='mdl-textfield__label'>Valider le mot de passe</label> </div></form>"

  $('#newSurvey').click(function(event) {event.preventDefault();showDialog({ title: "<span class='mdl-color-text--blue-800'>Ajouter un sondage</span>", text:contentNewSurvey, negative:false, positive: { title: 'Ajouter un sondage', onClick: function (e) { alert('Action performed!'); } } });});

  $('#login').click(function(event) {event.preventDefault();showDialog({ title: "<span class='mdl-color-text--blue-800'>Se connecter</span>", text:contentLogin, negative:false, positive: { title: 'Se connecter', onClick: function (e) { alert('Action performed!'); } } });});

  $('#signup').click(function(event) {event.preventDefault();showDialog({ title: "<span class='mdl-color-text--blue-800'>Créer un compte</span>", text:contentSignup, negative:false, positive: { title: 'Créer un compte', onClick: function (e) { alert('Action performed!'); } } });});

});
